var dd={
   "content":[
      {
         "columns":[
            {
               "text":"AGROTOOLS",
               "width":200,
               "color":"#16a825",
               "bold":true,
               "fontSize":28
            },
            [
               {
                  "text":"Orden de Trabajo",
                  "color":"#333333",
                  "width":"*",
                  "fontSize":20,
                  "bold":true,
                  "alignment":"right",
                  "margin":[
                     0,
                     0,
                     0,
                     15
                  ]
               },
                {
                  "stack":[
                     {
                        "columns":[
                           {
                              "text":"Orden N°",
                              "color":"#aaaaab",
                              "bold":true,
                              "width":"*",
                              "fontSize":12,
                              "alignment":"right"
                           },
                           {
                              "text":"000120",
                              "bold":true,
                              "color":"#333333",
                              "fontSize":12,
                              "alignment":"right",
                              "width":100
                           }
                        ]
                     }
                  ]
               }
               ,
               {
                  "stack":[
                     {
                        "columns":[
                           {
                              "text":"Fecha de Aplicacion",
                              "color":"#aaaaab",
                              "bold":true,
                              "width":"*",
                              "fontSize":12,
                              "alignment":"right"
                           },
                           {
                              "text":"12-05-2022",
                              "bold":true,
                              "color":"#333333",
                              "fontSize":12,
                              "alignment":"right",
                              "width":100
                           }
                        ]
                     }
                  ]
               }
            ]
         ]
      },
      {
         "columns":[
            [{
               "text":"Campo",
               "color":"#aaaaab",
               "bold":true,
               "fontSize":14,
               "alignment":"left",
               "margin":[
                  0,
                  20,
                  0,
                  5
               ]
            },
            {
               "text":"ELCAPO",
               "bold":true,
               "color":"#333333",
               "alignment":"left"
            },
            {
               "text":"Aplicador",
               "color":"#aaaaab",
               "bold":true,
               "fontSize":12,
               "alignment":"left",
               "margin":[
                  0,
                  20,
                  0,
                  5
               ]
            },
            {
               "text":"El Caballo SRL",
               "bold":true,
               "color":"#333333",
               "alignment":"left"
            },{
               "text":"20-1231323-1",
               "bold":true,
               "color":"#333333",
               "alignment":"left"
            },{
               "text":"Tel: 121-456",
               "bold":true,
               "color":"#333333",
               "alignment":"left"
            },
            
            ],
            [{
               "text":"Lotej",
               "color":"#aaaaab",
               "bold":true,
               "fontSize":14,
               "alignment":"left",
               "margin":[
                  0,
                  20,
                  0,
                  5
               ]
            },
            {
               "text":"Guklkjb",
               "bold":true,
               "color":"#333333",
               "alignment":"left"
            },
            ],
            {
               "image":"camposImg",
               width: 300,
               "margin":[
                  0,
                  10,
                  0,
                  5
               ]
            }
         ]
      },
     
      {
         "columns":[
            {
               "text":"",
               "color":"#aaaaab",
               "bold":true,
               "margin":[
                  0,
                  7,
                  0,
                  3
               ]
            },
            {
               "text":"",
               "color":"#aaaaab",
               "bold":true,
               "margin":[
                  0,
                  7,
                  0,
                  3
               ]
            }
         ]
      },
      {
         "columns":[
            {
               "text":"",
               "style":"invoiceBillingAddress"
            },
            {
               "text":"Ver Localización en Google Maps",
               link:"https://google.com",
            }
         ]
      },
      "\n\n",
      {
         "width":"100%",
         "alignment":"center",
         "text":"",
         "bold":true,
         "margin":[
            0,
            10,
            0,
            10
         ],
         "fontSize":15
      },
      {
         "layout":{
            "defaultBorder":false
         },
         "table":{
            "headerRows":1,
            "widths":[
               "auto",
               "*",
               "*",
               "*",
               "auto"
            ],
            "body":[
               [
                  {
                     "text":"Insumo",
                     "fillColor":"#eaf2f5",
                     "border":[
                        false,
                        true,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "textTransform":"uppercase"
                  },
                  {
                     "text":"Dosis",
                     "fillColor":"#eaf2f5",
                     "border":[
                        false,
                        true,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "textTransform":"uppercase"
                  },
                  {
                     "text":"Unidad",
                     "fillColor":"#eaf2f5",
                     "border":[
                        false,
                        true,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "textTransform":"uppercase"
                  },
                  {
                     "text":"Ha.",
                     "fillColor":"#eaf2f5",
                     "border":[
                        false,
                        true,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "textTransform":"uppercase"
                  },
                  {
                     "text":"Total Insumo",
                     "border":[
                        false,
                        true,
                        false,
                        true
                     ],
                     "alignment":"right",
                     "fillColor":"#eaf2f5",
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "textTransform":"uppercase"
                  }
               ],
               [
                  {
                     "text":"2,4-D 100 EC JEBAGRO",
                     "border":[
                        false,
                        false,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "alignment":"left"
                  },
                  {
                     "text":0,
                     "border":[
                        false,
                        false,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "alignment":"left"
                  },
                  {
                     "text":"lt/ha",
                     "border":[
                        false,
                        false,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "alignment":"left"
                  },
                  {
                     "text":83.61,
                     "border":[
                        false,
                        false,
                        false,
                        true
                     ],
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ],
                     "alignment":"left"
                  },
                  {
                     "border":[
                        false,
                        false,
                        false,
                        true
                     ],
                     "text":"0.00",
                     "fillColor":"#f5f5f5",
                     "alignment":"right",
                     "margin":[
                        0,
                        5,
                        0,
                        5
                     ]
                  }
               ]
            ]
         }
      },
      "\n",
      "\n\n",
      {
         "text":"Comentarios",
         "style":"notesTitle"
      },
      {
         "text":"Hjihh",
         "style":"notesText"
      }
   ],
   "styles":{
      "notesTitle":{
         "fontSize":10,
         "bold":true,
         "margin":[
            0,
            50,
            0,
            3
         ]
      },
      "notesText":{
         "fontSize":10
      }
   },
   "defaultStyle":{
      "columnGap":20
   },
   "images":{
      "camposImg":"https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/geojson(%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22geometry%22%3A%7B%22coordinates%22%3A%5B%5B%5B-59.26097%2C-35.20633%5D%2C%5B-59.23814%2C-35.20521%5D%2C%5B-59.2323%2C-35.21404%5D%2C%5B-59.24895%2C-35.22204%5D%2C%5B-59.26097%2C-35.20633%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%2C%22properties%22%3A%7B%22fill-opacity%22%3A0%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22geometry%22%3A%7B%22coordinates%22%3A%5B%5B%5B-59.25671%2C-35.20768%5D%2C%5B-59.24773%2C-35.21713%5D%2C%5B-59.24252%2C-35.21133%5D%2C%5B-59.24355%2C-35.20656%5D%2C%5B-59.25671%2C-35.20768%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%2C%22properties%22%3A%7B%22stroke%22%3A%22%234e9a06%22%2C%22stroke-width%22%3A4%2C%22stroke-opacity%22%3A1%2C%22fill%22%3A%22%234e9a06%22%2C%22fill-opacity%22%3A0.8%7D%7D%5D%7D)/auto/500x300?access_token=pk.eyJ1IjoibGF6bG9wYW5hZmxleCIsImEiOiJja3ZzZHJ0ZzYzN2FvMm9tdDZoZmJqbHNuIn0.oQI_TrJ3SvJ6e5S9_CnzFw"
   }
}