import "../navbar-element/new-app-layout";
import "../mapa-principal/mapa-principal";
import "../news-bar/news-bar";
import("../sensores/sensores-offcanvas");
import("../nueva-geometria/nueva-geometria");
import "../nuevo-campo/nuevo-campo";
import("../recorridas/nota-target");
import("../lote-offcanvas/repetir-aplicacion/repetir-aplicacion");
import("../lista-centrales-cercanas/lista-centrales-cercanas");
import("../sensores/lista-de-sensores");
// import("../invite/invite");
import ("../sensores/devices-route");